// Regenerate the committed tree-canvas fixture (packages/web/fixtures/canvas-diff.*.json).
//
// Why this exists (intake/web-ui/08-fork-prep.md task 6): the canvas track (06) must be
// developable with NO LuaJIT and NO pob-runtime submodule checkout. So one real repair run is
// captured to JSON here and committed. Re-run only when the optimiser output shape or the
// reference build changes:
//
//   npx ts-node spike/genCanvasFixture.ts "<build.xml>" [respecBudget] [outfile]
//
// Defaults reproduce the phase-1 verification-gate run:
//   build        D:/My Documents/Path of Building (PoE2)/Builds/ninja/R_Thor-L84-weak.xml
//   respecBudget 3   (repair mode; default objective TotalDPS, proximity 3, Notable/Keystone)
//
// `afterConnected` is the EXACT connected post-plan allocated-node id set, path/traversal nodes
// included -- from `optimiseTree`'s `allocatedNodeIds.after`, which since the 2026-08-29 bridge
// change is `list_allocated_nodes({ removeIds: <dropped>, allocSet: <picks> })`: the bridge
// deallocs the removal cascade, allocs the picks (AllocNode auto-paths), rebuilds paths, and
// lists `spec.allocNodes` -- a connected set by construction. The fixture still also ships
// `afterPicksOnly = before - removedCascade + picks` (picks only, no traversal nodes) for
// comparison, and `unloggedPathNodeCount = afterConnected.length - afterPicksOnly.length`
// (equivalently sum(step.pointsSpent) - steps.length) -- how many traversal nodes the picks-only
// set was missing.

import * as fs from "node:fs";
import * as path from "node:path";
import { PobBridge } from "@poe2/pob-bridge";
import { loadBuildFromFile } from "../src/core/loadBuild";
import { optimiseTree } from "../src/core/optimiseTree";

interface AllocatedNode {
  id: number;
  name: string;
  type: string;
  statLines: string[];
  ascendancyName?: string;
}

const DEFAULT_BUILD = "D:/My Documents/Path of Building (PoE2)/Builds/ninja/R_Thor-L84-weak.xml";

async function main(): Promise<void> {
  const buildXmlPath = process.argv[2] ?? DEFAULT_BUILD;
  const respecBudget = process.argv[3] ? Number(process.argv[3]) : 3;
  const outFile =
    process.argv[4] ??
    path.resolve(
      __dirname,
      `../packages/web/fixtures/canvas-diff.${path.basename(buildXmlPath).replace(/\.xml$/i, "")}.json`,
    );

  if (!fs.existsSync(buildXmlPath)) {
    throw new Error(`build XML not found: ${buildXmlPath}`);
  }

  const t0 = Date.now();
  const bridge = new PobBridge();
  try {
    await loadBuildFromFile(bridge, buildXmlPath);
    await bridge.call("reset_metrics");

    const status = await bridge.call<{ pointsUsed: number; pointsMax: number; treeNodesAllocated: number }>(
      "get_tree_status",
    );
    const before = await bridge.call<{ nodes: AllocatedNode[] }>("list_allocated_nodes");
    const beforeIds = before.nodes.map((n) => n.id).sort((a, b) => a - b);

    const options = { respecBudget } as Parameters<typeof optimiseTree>[1];
    const result = await optimiseTree(bridge, options);

    const removedIds = result.removed.map((r) => r.id);
    // Exact "before minus the removed nodes and their downstream cascades".
    const postRemoval =
      removedIds.length > 0
        ? await bridge.call<{ nodes: AllocatedNode[] }>("list_allocated_nodes", { removeIds: removedIds })
        : before;
    const postRemovalIds = postRemoval.nodes.map((n) => n.id).sort((a, b) => a - b);
    const removedCascadeIds = beforeIds.filter((id) => !postRemovalIds.includes(id));

    const addedPickIds = [...result.addedNodeIds].sort((a, b) => a - b);
    const afterPicksOnly = [...new Set([...postRemovalIds, ...addedPickIds])].sort((a, b) => a - b);

    // The exact connected post-plan set, straight off optimiseTree (bridge-derived, ascending).
    const afterConnected = result.allocatedNodeIds.after;
    // The traversal nodes afterPicksOnly was missing. Also equals sum(step.pointsSpent) - steps.length.
    const unloggedPathNodeCount = afterConnected.length - afterPicksOnly.length;

    const metrics = await bridge.call<{ buildOutputCount?: number }>("get_metrics").catch(() => ({}) as { buildOutputCount?: number });

    const fixture = {
      meta: {
        purpose:
          "Tree-canvas diff fixture. Lets intake/web-ui/06-tree-canvas.md be built with no LuaJIT " +
          "and no pob-runtime submodule. Generated by spike/genCanvasFixture.ts.",
        build: path.basename(buildXmlPath),
        buildPath: buildXmlPath,
        command: `npx ts-node spike/genCanvasFixture.ts "${buildXmlPath}" ${respecBudget}`,
        generatedAt: new Date().toISOString(),
        wallSeconds: Math.round((Date.now() - t0) / 100) / 10,
        buildOutputs: metrics.buildOutputCount ?? result.buildOutputCount ?? null,
        treeVersion: "0_5",
        note:
          "afterConnected is the exact connected post-plan allocated set (path nodes included), " +
          "from optimiseTree.allocatedNodeIds.after (list_allocated_nodes with allocSet+removeIds, " +
          "added 2026-08-29). afterPicksOnly is kept for comparison; unloggedPathNodeCount is how " +
          "many traversal nodes it was missing.",
      },
      baseline: {
        pointsUsed: status.pointsUsed,
        pointsMax: status.pointsMax,
        treeNodesAllocated: status.treeNodesAllocated,
        objective: result.baseline.objective,
      },
      anchor: result.anchorNodeId ?? null,
      before: beforeIds,
      removedCascadeIds,
      removed: result.removed.map((r) => ({
        id: r.id,
        name: r.name,
        type: r.type,
        pointsFreed: r.pointsFreed,
        valueLost: r.valueLost,
        anchorCascade: r.anchorCascade ?? false,
      })),
      addedPickIds,
      steps: result.steps.map((s) => ({
        id: s.id,
        name: s.name,
        type: s.type,
        pointsSpent: s.pointsSpent,
        pathLength: s.pathLength ?? null,
        objectiveBefore: s.objectiveBefore,
        objectiveAfter: s.objectiveAfter,
        statLines: s.statLines,
      })),
      afterPicksOnly,
      afterConnected,
      unloggedPathNodeCount,
      result: {
        mode: result.mode,
        respecBudget: result.respecBudget ?? null,
        stoppedBecause: result.stoppedBecause,
        pointsFreed: result.pointsFreed,
        pointsRespent: result.pointsRespent,
        finalObjective: result.final.objective,
        netPointsSpent: result.final.pointsSpent,
        buildOutputCount: result.buildOutputCount ?? null,
        cacheHitRate: result.cacheHitRate,
      },
    };

    fs.mkdirSync(path.dirname(outFile), { recursive: true });
    fs.writeFileSync(outFile, JSON.stringify(fixture, null, 2) + "\n");
    console.log(
      `wrote ${outFile}\n` +
        `  before ${beforeIds.length}  removedCascade ${removedCascadeIds.length}  ` +
        `addedPicks ${addedPickIds.length}  afterPicksOnly ${afterPicksOnly.length}  ` +
        `afterConnected ${afterConnected.length}  unloggedPathNodes ${unloggedPathNodeCount}\n` +
        `  stoppedBecause=${result.stoppedBecause}  objective ${result.baseline.objective} -> ${result.final.objective}\n` +
        `  BuildOutputs=${fixture.meta.buildOutputs}  wall=${fixture.meta.wallSeconds}s`,
    );
  } finally {
    bridge.dispose();
  }
}

main().catch((err) => {
  console.error(err instanceof Error ? err.stack : err);
  process.exitCode = 1;
});
