// Regenerate the committed tree-canvas fixture (packages/web/fixtures/canvas-diff.*.json).
//
// Why this exists (docs/web-ui/08-fork-prep.md task 6): the canvas track (06) must be
// developable with NO LuaJIT and NO pob-runtime submodule checkout. So one real repair run is
// captured to JSON here and committed. Re-run only when the optimiser output shape or the
// reference build changes:
//
//   npx ts-node spike/genCanvasFixture.ts "<build.xml>" [respecBudget] [outfile]
//
// Defaults reproduce the phase-1 verification-gate run:
//   build        D:/My Documents/Path of Building (PoE2)/Builds/ninja/R_Thor-L84-weak.xml
//   respecBudget 3   (repair mode; default objective TotalDPS, proximity 3, Notable/Keystone)
//
// KNOWN LIMITATION captured in the fixture as `afterConnected: null`:
// there is currently no way to obtain the EXACT post-plan allocated-node id set (path/traversal
// nodes included). `optimiseTree` is a pure planner -- it never leaves the bridge in the
// post-plan state -- `result.addedNodeIds` is picks-only (path nodes AllocNode drags in are not
// listed), and `PassiveSpec:ImportFromNodeList` allocates exactly the ids it is given (it does
// not auto-path). No bridge RPC returns an allocated set for a given allocSet either. So the
// fixture ships `before` (exact), `removedCascadeIds` (exact, via list_allocated_nodes'
// removeIds), `addedPickIds` (exact, picks only) and `afterPicksOnly = before - removed +
// picks`. `unloggedPathNodeCount` records how many traversal nodes that set is missing. Fill in
// `afterConnected` once a bridge method can enumerate the connected post-plan set.

import * as fs from "node:fs";
import * as path from "node:path";
import { PobBridge } from "@poe2/pob-bridge";
import { loadBuildFromFile } from "../src/core/loadBuild";
import { optimiseTree } from "../src/core/optimiseTree";

interface AllocatedNode {
  id: number;
  name: string;
  type: string;
  statLines: string[];
  ascendancyName?: string;
}

const DEFAULT_BUILD = "D:/My Documents/Path of Building (PoE2)/Builds/ninja/R_Thor-L84-weak.xml";

async function main(): Promise<void> {
  const buildXmlPath = process.argv[2] ?? DEFAULT_BUILD;
  const respecBudget = process.argv[3] ? Number(process.argv[3]) : 3;
  const outFile =
    process.argv[4] ??
    path.resolve(
      __dirname,
      `../packages/web/fixtures/canvas-diff.${path.basename(buildXmlPath).replace(/\.xml$/i, "")}.json`,
    );

  if (!fs.existsSync(buildXmlPath)) {
    throw new Error(`build XML not found: ${buildXmlPath}`);
  }

  const t0 = Date.now();
  const bridge = new PobBridge();
  try {
    await loadBuildFromFile(bridge, buildXmlPath);
    await bridge.call("reset_metrics");

    const status = await bridge.call<{ pointsUsed: number; pointsMax: number; treeNodesAllocated: number }>(
      "get_tree_status",
    );
    const before = await bridge.call<{ nodes: AllocatedNode[] }>("list_allocated_nodes");
    const beforeIds = before.nodes.map((n) => n.id).sort((a, b) => a - b);

    const options = { respecBudget } as Parameters<typeof optimiseTree>[1];
    const result = await optimiseTree(bridge, options);

    const removedIds = result.removed.map((r) => r.id);
    // Exact "before minus the removed nodes and their downstream cascades".
    const postRemoval =
      removedIds.length > 0
        ? await bridge.call<{ nodes: AllocatedNode[] }>("list_allocated_nodes", { removeIds: removedIds })
        : before;
    const postRemovalIds = postRemoval.nodes.map((n) => n.id).sort((a, b) => a - b);
    const removedCascadeIds = beforeIds.filter((id) => !postRemovalIds.includes(id));

    const addedPickIds = [...result.addedNodeIds].sort((a, b) => a - b);
    const afterPicksOnly = [...new Set([...postRemovalIds, ...addedPickIds])].sort((a, b) => a - b);

    // How many traversal nodes afterPicksOnly is missing: price the whole re-spend set against
    // the post-removal tree; net pointsSpent is (real nodes added) - (points freed).
    let unloggedPathNodeCount: number | null = null;
    try {
      const priced = await bridge.call<{ pointsSpent: number }>("get_stats_from", {
        allocSet: addedPickIds,
        removeIds: removedIds,
      });
      // real added = net + freed ; picks-only added = addedPickIds.length
      const realAdded = priced.pointsSpent + result.pointsFreed;
      unloggedPathNodeCount = Math.max(0, realAdded - addedPickIds.length);
    } catch {
      /* older bridge without get_stats_from -- leave null */
    }

    const metrics = await bridge.call<{ buildOutputCount?: number }>("get_metrics").catch(() => ({}) as { buildOutputCount?: number });

    const fixture = {
      meta: {
        purpose:
          "Tree-canvas diff fixture. Lets docs/web-ui/06-tree-canvas.md be built with no LuaJIT " +
          "and no pob-runtime submodule. Generated by spike/genCanvasFixture.ts.",
        build: path.basename(buildXmlPath),
        buildPath: buildXmlPath,
        command: `npx ts-node spike/genCanvasFixture.ts "${buildXmlPath}" ${respecBudget}`,
        generatedAt: new Date().toISOString(),
        wallSeconds: Math.round((Date.now() - t0) / 100) / 10,
        buildOutputs: metrics.buildOutputCount ?? result.buildOutputCount ?? null,
        treeVersion: "0_5",
        limitation:
          "afterConnected is null: no current way to enumerate the EXACT connected post-plan " +
          "allocated set (path nodes included). See the header of spike/genCanvasFixture.ts. " +
          "Use afterPicksOnly (missing ~unloggedPathNodeCount traversal nodes) until that lands.",
      },
      baseline: {
        pointsUsed: status.pointsUsed,
        pointsMax: status.pointsMax,
        treeNodesAllocated: status.treeNodesAllocated,
        objective: result.baseline.objective,
      },
      anchor: result.anchorNodeId ?? null,
      before: beforeIds,
      removedCascadeIds,
      removed: result.removed.map((r) => ({
        id: r.id,
        name: r.name,
        type: r.type,
        pointsFreed: r.pointsFreed,
        valueLost: r.valueLost,
        anchorCascade: r.anchorCascade ?? false,
      })),
      addedPickIds,
      steps: result.steps.map((s) => ({
        id: s.id,
        name: s.name,
        type: s.type,
        pointsSpent: s.pointsSpent,
        pathLength: s.pathLength ?? null,
        objectiveBefore: s.objectiveBefore,
        objectiveAfter: s.objectiveAfter,
        statLines: s.statLines,
      })),
      afterPicksOnly,
      afterConnected: null,
      unloggedPathNodeCount,
      result: {
        mode: result.mode,
        respecBudget: result.respecBudget ?? null,
        stoppedBecause: result.stoppedBecause,
        pointsFreed: result.pointsFreed,
        pointsRespent: result.pointsRespent,
        finalObjective: result.final.objective,
        netPointsSpent: result.final.pointsSpent,
        buildOutputCount: result.buildOutputCount ?? null,
        cacheHitRate: result.cacheHitRate,
      },
    };

    fs.mkdirSync(path.dirname(outFile), { recursive: true });
    fs.writeFileSync(outFile, JSON.stringify(fixture, null, 2) + "\n");
    console.log(
      `wrote ${outFile}\n` +
        `  before ${beforeIds.length}  removedCascade ${removedCascadeIds.length}  ` +
        `addedPicks ${addedPickIds.length}  afterPicksOnly ${afterPicksOnly.length}  ` +
        `unloggedPathNodes ${unloggedPathNodeCount ?? "?"}\n` +
        `  stoppedBecause=${result.stoppedBecause}  objective ${result.baseline.objective} -> ${result.final.objective}\n` +
        `  BuildOutputs=${fixture.meta.buildOutputs}  wall=${fixture.meta.wallSeconds}s`,
    );
  } finally {
    bridge.dispose();
  }
}

main().catch((err) => {
  console.error(err instanceof Error ? err.stack : err);
  process.exitCode = 1;
});
